# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=250)),
                ('Descricao', models.CharField(max_length=350)),
                ('Imagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=250)),
                ('Descricao', models.CharField(max_length=100)),
                ('Ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Ocupacao')),
            ],
        ),
    ]
