# Generated by Django 2.1.3 on 2018-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_pessoa_frequente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacao',
            name='DescricaoLong',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
